config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  
  

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]

  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get "/search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params["model"]
    @content = params["content"]
    @method = params["method"]
    if @model == 'user'
      @records = User.search_for(@content, @method)
    else
      @records = Book.search_for(@content, @method)
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_search.html.erb
<div class="search_form">
  <%= form_with url: search_path, local: true, method: :get do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book" }) %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit '検索' %>
  <% end %>
</div>

app/views/searches/search.html.erb
<div class="body">
  <div class="container">
    <div class="row">
      <div class="col-xs-10">

        <% if @model == "user" %>
          <h2>Users search for "<%= @content %>"</h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th>image</th>
                <th>name</th>
              </tr>
            </thead>
            <tbody>
            <tr>
            <% @records.each do |user| %>
              <td>
                <%= image_tag user.get_profile_image, size: '50x50' %>
              </td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user.id) %></td>
            <% end %>
            </tr>
            </tbody>
          </table>
        <% else %>
          <h2>Books search for <%= @content %></h2>
          <table class="table table-hover table-inverse">
            <thead>
              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
              </tr>
            </thead>
            <tbody>
            <tr>
            <% @records.each do |book| %>
              <td>
                <%= image_tag book.user.get_profile_image,  size: '50x50' %>
              </td>
              <td><%= book.title %></td>
              <td><%= link_to "Show", book_path(book.id) %></td>
            <% end %>
            </tr>
            </tbody>
          </table>
        <% end %>

      </div>
    </div>
  </div>
</div>